language: node_js
node_js:
- 10.8.0
services:
- mongodb
script:
- npm run test
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: &1
    secure: p6SkguJridEJmAfbpKwL5LEVphCRhhDpcNH7teYCj0WYuOrh21edxGjd9NsasnuqsXxeOjzTn7hCFB4jn6G02wEzoAjDgLrR/PI94kn5xAfpXDf/1CKQGLd0RTwGwjJ6XpVz63encc1jhDWnsa6JpndhqVE7dRQkqSPylTpTvi4lMr6fdH1b+yt6YzUKuzUmo6TP36njhKeH/Wv7MF23Uc0R+WJU1DLov1wSVPnLJcBFbg+K3tDU3bQiU8slVWjLDbgS7MAQLGZyHGXGQv5qzJmma9EVBVewmOKhAna94dcFL8uSZMCOJDDvcYMk7Tph/smk8kB9/B93iYGooOgRGuJgDQOYaTqHGeSukR5LSBnzIqcPbjdaIbyIseu0t3oZZQQfwRiYIUEuxNQC6f9Z5rlk77nWkctKSDQCWCGMB7oZKnSj4cYWdapsds3c3EUK3k2DzexzrfEjHthXz+weuOJCZKEwc0BHksZmlKfvvUy4wQlwLnJG6Zc76DUtG9YHionwEjrZfOjrKL9O/Yn2PDriKGwc51ECq3dq8aF24uzvklyQyy+1XO1pYvGnGX82odWUl5lTmDt/FkN7sLrQtUdtkwuacVE5LKqPBz0Bry+LVa5gURKGchbNJMfs6RemGY/5UWTFh/B5HMpbVojeNpD3nxSFsOeCbR25bj1LAtc=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: valworbli/apitestdeploy
  bucket: $S3_DEV_API_BUCKET_NAME
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: *1
  bucket: $S3_DEV_API_BUCKET_NAME
  key: $AWS_ACCESS_KEY_ID
  bundle_type: OdgWPyKripoldEVRrm3O9adzCODHeDR2x6ePfFVQ
  application: $AWS_CODE_DEPLOY_APPLICATION
  deployment_group: $AWS_CODE_DEPLOY_DEPLOYMENT_GROUP
  on: *2
before_deploy:
- mkdir -p dpl_cd_upload
- mv $AWS_ACCESS_KEY_ID dpl_cd_upload/$AWS_ACCESS_KEY_ID
