language: node_js
node_js:
- 10.8.0
services:
- mongodb
script:
- npm run test
before_install:
- openssl aes-256-cbc -d -pass env:ENV_PASS -in env.encoded -out .env
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: valworbli/apitestdeploy
  bucket: $S3_DEV_API_BUCKET_NAME
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_DEV_API_BUCKET_NAME
  key: $AWS_ACCESS_KEY_ID
  bundle_type: $AWS_SECRET_ACCESS_KEY
  application: $AWS_CODE_DEPLOY_APPLICATION
  deployment_group: $AWS_CODE_DEPLOY_DEPLOYMENT_GROUP
  on: *2
before_deploy:
- mkdir -p dpl_cd_upload
- mv $AWS_ACCESS_KEY_ID dpl_cd_upload/$AWS_ACCESS_KEY_ID
