version: 0.0

os: linux

files:
  - source: ./
    destination: /home/ubuntu/portal/portalBackEnd/

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 30
      runas: root
  # AfterInstall:
  #   - location: scripts/change_permissions.sh
  #     timeout: 300
  #     runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 30
      runas: root
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: root